version: '3.8'
services:
  api:
    image: cbeurtheret/myhome-api
    restart: always
    build:
      context: .
      target: production
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - prodnet
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'myhome'
      MYSQL_USER: 'myhome-user'
      MYSQL_PASSWORD: '34XZBhrLotxdXcKl'
      MYSQL_ROOT_PASSWORD: 'B5p49Wd98adDqjJY'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - prodnet
    volumes:
      - my-db-prod:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

networks:
  prodnet:

volumes:
  my-db-prod:
